<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260212151342 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE event_store (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, aggregate_id INT NOT NULL, aggregate_type VARCHAR(255) NOT NULL, event_name VARCHAR(255) NOT NULL, payload JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, version INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BE4CE95BD0BBCCBE ON event_store (aggregate_id)');
        $this->addSql('CREATE INDEX IDX_BE4CE95BD0BBCCBEBF1CD3C3 ON event_store (aggregate_id, version)');
        $this->addSql('CREATE INDEX IDX_BE4CE95B8B8E8428 ON event_store (created_at)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE event_store');
    }
}
